### ISSUE TITLE
Long password issue [low priority]

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#1]
This is low priority because most users won't use very long passwords unless they have a password manager that creates long passwords.

Setup: Win7x86, ExcelPass 1.6.2.1

Steps:
1. Launch program and add .DOCX file
2. Use long password (30 characters)

Defect: program crash

![2016-08-03 19_39_29-excelpass](https://cloud.githubusercontent.com/assets/1289134/17386677/8555469a-59b2-11e6-86cf-bb9e4f300c96.png)

**Comment by fukuyori** [comment]
The Word's password There is a 15-character limit. 
If the 16 or more characters of the password when you try to set the word file, an error occurs.

**Comment by vatterspun** [comment]
Ah I wasn't aware.  Maybe this should be a feature request for a 15-character password warning for Microsoft Office files?  Anyway, I'll close the issue.
