### ISSUE TITLE
[Feature Request] "No-install" version

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#10]
**Current behavior:**

Program must be installed to use.

**Requested behavior:**

A version that is just the necessary files that are remaining after install.

![2017-01-19 18_49_27-excelpass](https://cloud.githubusercontent.com/assets/1289134/22131304/096b5e3e-de78-11e6-9c17-6ea950f3a394.png)

Just the files above in a zip file.  Could be distributed on GITHUB as ExcelPass_1.7.1.1-no_install.zip

**Background:**

Currently, PortableFreeware.com is [listing your program](https://www.portablefreeware.com/index.php?id=2802) in concert with the Universal Extractor program to skip the installation process.  It would be helpful to have a version available that doesn't need extraction.

Also, the installer is not in English, though the resulting program is.

![2017-01-19 18_43_00-excelpass z b g a b v](https://cloud.githubusercontent.com/assets/1289134/22131202/217e8f06-de77-11e6-8ba2-4d6fb1e6dac2.png)

**Comment by fukuyori** [comment]
I made it possible to select English and Japanese for the installer.
And no installer version add.

**Comment by vatterspun** [comment]
Awesome, thank you
