### ISSUE TITLE
[Feature Request] Add entire folder and subfolders

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#11]
[Note: this is low priority]

**Current behavior**

To add all the files from a folder, you must open the folder and select them.  For subfolders, you must select all items in their respective subfolders.  This can be very time-consuming.

**Requested behavior**

1. Drag-and-drop a folder with multiple files and subfolders
2. All compatible files appear in the interface where the author can password protect them

**Workaround**

Use a program like [Everything](https://www.portablefreeware.com/index.php?id=1479) and enter in the directory and extention (e.g. _c:\test .xlsx_) . Drag-and-drop all found items into the ExcelPass interface.

**Potential issues**

* Users may password-protect a file or folder they didn't mean to
* It may make more sense to create a single zip file and then use ExcelPass to create a password for it

**Comment by fukuyori** [comment]
I made it possible in version 1.7.3.1

**Comment by vatterspun** [comment]
Confirmed.  Tested to a depth of 3 folders with all compatible file types and it worked fine.

Thanks for adding that :)
