### ISSUE TITLE
[Feature Request] Stop on error

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#14]
I'm not sure this is a good idea or not, but when protecting files with a password, it might make sense to keep protecting files and leave the unprocessed files as a list.

This could be solved with a manual describing the "Clear" process:

![2017-02-07 19_46_22-excelpass](https://cloud.githubusercontent.com/assets/1289134/22720036/1c78c9f8-ed6e-11e6-9690-058a17f1afd8.png)

... or with the following feature:

**Current behavior**

When password-protecting a list of files, the program will stop if it encounters an error, the process freezes on that file (as below):

![2017-02-07 19_42_08-excelpass](https://cloud.githubusercontent.com/assets/1289134/22720007/e0aada10-ed6d-11e6-89a8-a0e855c2aa95.png)

**Requested capability**

Ability to continue processing files.  

**Interface suggestion**

A checkbox at the bottom of the window that is checked by default labeled "Stop on error" or unchecked for "continue processing on error".  See rough mockup below:

![2017-02-07 19_51_24-presentation1 - microsoft powerpoint](https://cloud.githubusercontent.com/assets/1289134/22720176/ecabe39e-ed6e-11e6-8a82-d373ea380272.png)

**Comment by fukuyori** [comment]
Certainly it is not smart to interrupt processing every time an error occurs.
It seems to keep working smoothly, leaving files that can not be processed and continuing processing.
But It is necessary to change how to display error messages.
I’ll consider it.

**Comment by vatterspun** [comment]
The current interface is simple and I think that's a real asset.  Additions that aren't really necessary might not make sense.  I debated posting this for some time so if it doesn't make sense to add, that's fine.

**Comment by vatterspun** [comment]
I've given this some thought and I don't think it makes sense to add to the main interface.  I can imagine it being added to an advanced options menu in the future, but I just can't shake the idea that this makes a wonderfully simple security program too complex.  Closing the issue.
