### ISSUE TITLE
"File is busy" error msg [low priority]

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#2]
NOTE: This issue appeared to go away after about 10 mins.

---

This is connected to the [Long Password issue ](https://github.com/fukuyori/ExcelPass/issues/1)on the same system setup.

This 

Steps: 
1. Add the file that was used when the program crashed in the last example, use a smaller password

Defect: Get "File is busy" error msg

![2016-08-03 19_42_01-excelpass](https://cloud.githubusercontent.com/assets/1289134/17386725/f5ceba1e-59b2-11e6-8b1e-e2c93c8f7ec0.png)

**Comment by fukuyori** [comment]
Perhaps, 
It seems that it is caused by the termination processing of the word file.
I will fix it in the next release (version 1.7.3.2).

**Comment by fukuyori** [comment]
Perhaps,
This is probably because the word file termination processing is not correctly done when encrypting it.
I will fix it in the next release (version 1.7.3.2).

**Comment by vatterspun** [comment]
Closing this case since the long password issue has been resolved.
