### ISSUE TITLE
About menu cut off [low priority]

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#3]
Setup: Win7x86

Steps:
1. Launch program and click on the ? icon

Defect: "About" menu window not displaying in full

![2016-08-03 19_51_33-version information](https://cloud.githubusercontent.com/assets/1289134/17386815/bd451232-59b3-11e6-8ca2-2854b6c8ffca.png)

**Comment by fukuyori** [comment]
Fixed in version 1.7.1.1

**Comment by vatterspun** [comment]
Great news, thanks.

**Comment by vatterspun** [comment]
Tested 1.7.1.1 - issue resolved.  Closing.
