### ISSUE TITLE
Feature request: process complete message

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#4]
**Current behavior**

Files that are password-protected disappear from the list.

**Requested behavior**

A notice at the top or bottom of the window that a read, write, or read and write password was set.

Possible appearance:

![2016-08-03 19_54_57-clipboard](https://cloud.githubusercontent.com/assets/1289134/17386888/589b999a-59b4-11e6-9d09-01693aba56b9.png)

**Comment by fukuyori** [comment]
Sorry, It is the specification of this application .

**Comment by fukuyori** [comment]
That request was added in version 1.7.3.4.

**Comment by vatterspun** [comment]
Outstanding 👍

**Comment by vatterspun** [comment]
Verified in 1.7.3.4 -- closing issue.
