### ISSUE TITLE
Translation edit: unencrypted PDF

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#7]
Currently, when trying to decrypt a PDF that is not encrypted, the program gives the error message 

> This pdf file is not applied password.

I think a better translation would be "This PDF file does not have an applied password"

**Comment by fukuyori** [comment]
Fixed in version 1.7.1.1

**Comment by vatterspun** [comment]
Glad that helped :)

**Comment by vatterspun** [comment]
Tested 1.7.1.1 - issue resolved. Closing.
