### ISSUE TITLE
Write Password for Excel xlsx file

### ISSUE THREAD

**Issue by fukuyori** [fukuyori/ExcelPass#8]
I cant set to write password to excel xlsx file.
It works well in the case of xls file.

**Comment by fukuyori** [comment]
Perhaps, by the .net update program (published May 4, 2016), it seems that failure has occurred.

**Comment by vatterspun** [comment]
I tested with v1.7.1.1 ... adding a "read" password works to restrict XLSX files.  Adding a "write" password does not.

Both DOCX and PPTX both work as expected.

**Comment by fukuyori** [comment]
Fixed in version 1.7.2.1

**Comment by vatterspun** [comment]
Fix confirmed.  Feel free to close the issue.
