### ISSUE TITLE
Feature request: notice of 15 character limit for Microsoft Office files

### ISSUE THREAD

**Issue by vatterspun** [fukuyori/ExcelPass#9]
It might be helpful to give notice when someone is trying to password-protect a Microsoft Office file that more than 15 character passwords aren't supported.

**Current behavior**: Error message https://github.com/fukuyori/ExcelPass/issues/1

**Requested behavior**: Possible changes:
- Descriptive error message
- Notice about limit on program interface when Microsoft file types are added
- Entry typing is limited to 15 characters

**Comment by fukuyori** [comment]
I restricted the write password length to 15 characters in version 1.7.3.1

**Comment by vatterspun** [comment]
:) Great, thanks ... tested and it works great.
